# -*- coding: utf-8 -*-
"""ListaExercicio4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FcDNL_riQMPOuQVxiwpp7es1nV0W6vWb

# 📊 Projeto Final – Análise Contábil com Ajuste Econômico

Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.

1) Configure o título na barra do navegador, da página do projeto no Streamlit e descrição inicial do projeto (peso: 1,0)

- Título na barra (`page_title`): Lista de Exercícios 4
- Título da página (`header`): Projeto Final – Análise Contábil com Ajuste Econômico
- Descrição projeto (`write`): Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos, utilizando Python, Pandas, Ipeadata e Streamlit.

2) Importe os dados do arquivo empresas_dados.csv utilizando pandas e apresente todas as linhas da df (peso: 1,0)

Dica: Utilize `head(len(df))`
"""

import streamlit as st
import pandas as pd

st.set_page_config(
    page_title="Lista de Exercícios 4",
    layout="centered"
)

st.header("Projeto Final – Análise Contábil com Ajuste Econômico")

st.write("""
Este projeto tem como objetivo integrar análise de dados contábeis de empresas com indicadores econômicos,
utilizando Python, Pandas, Ipeadata e Streamlit.
""")

df = pd.read_csv('empresas_dados.csv')

st.subheader('Todas as Linhas da Tabela')
st.dataframe(df)

"""3) Calcule os indicadores Margem Líquida e ROA e salve como novas coluna da df. Depois apresente os dois indicadores no mesmo gráfico de linhas, agrupado por Ano  (peso: 1,0)

- Margem Líquida = Lucro Líquido / Receita Líquida * 100
- ROA = Lucro Líquido / Ativo Total *  100
"""

import pandas as pd
import matplotlib.pyplot as plt
import streamlit as st

st.set_page_config(
    page_title="Lista de Exercícios 4 - Indicadores",
    layout="centered"
)

st.header("Projeto Final – Análise Contábil com Ajuste Econômico")

df = pd.read_csv('empresas_dados.csv', delimiter=';')

st.subheader("Colunas do DataFrame")
st.write(df.columns.tolist())

st.subheader("Visualização dos Primeiros Registros")
st.dataframe(df.head())

df['Margem Líquida'] = (df['Lucro Líquido'] / df['Receita Líquida']) * 100
df['ROA'] = (df['Lucro Líquido'] / df['Ativo Total']) * 100

df_grouped = df.groupby('Ano')[['Margem Líquida', 'ROA']].mean().reset_index()

fig, ax = plt.subplots(figsize=(10, 6))
ax.plot(df_grouped['Ano'], df_grouped['Margem Líquida'], marker='o', label='Margem Líquida (%)')
ax.plot(df_grouped['Ano'], df_grouped['ROA'], marker='o', label='ROA (%)')
ax.set_title('Margem Líquida e ROA ao longo dos anos')
ax.set_xlabel('Ano')
ax.set_ylabel('Percentual (%)')
ax.legend()
ax.grid()
ax.set_xticks(df_grouped['Ano'])

st.pyplot(fig)

"""4) Utilize o pacote ipeadatapy e faça busca para encontrar o indicador que traga o IPCA, taxa de variação, em % e anual: (peso: 2,0)

- Baixe os dados no período de 2010 a 2024
- Altere o nome da coluna "YEAR" para "Ano"
- Altere o nome da coluna "VALUE ((% a.a.))" para "IPCA"
- Apresente a df para checar se tudo deu certo
"""

import streamlit as st
import pandas as pd
import ipeadatapy as ip

df_ipea = ip.timeseries('PRECOS12_IPCA12')
df_ipea = df_ipea.reset_index()
df_ipea = df_ipea[df_ipea['YEAR'].between(2010, 2024)]
df_ipea = df_ipea.rename(columns={'YEAR': 'Ano', 'VALUE (-)': 'IPCA'})
df_ipea = df_ipea[['Ano', 'IPCA']]

df_excel = pd.read_csv('empresas_dados.csv', delimiter=';')

df_combinada = pd.merge(df_excel, df_ipea, on='Ano', how='inner')

df_combinada['Receita Real'] = df_combinada['Receita Líquida'] - (
    df_combinada['Receita Líquida'] * (df_combinada['IPCA'] / 100)
)

st.subheader("Tabela com Receita Real ajustada pela inflação (IPCA)")
st.dataframe(df_combinada)

"""5) Combine as duas df (Excel e IPEA) em uma nova df e calcule nova coluna chamada Receita Real (peso: 2,0)

- Utilize a função `pd.merge()` para unificar as duas df utiilizando a coluna Ano como conexão (chave primária) entre elas
- Crie nova coluna chamada Receita Real que será o resultado da Receita Líquida de cada ano deduzido o IPCA do ano: `Receita Real = Receitta Líquida - ( Receita Líquida * (IPCA/100) )`
- Apresente a nova df combinada

"""

import streamlit as st
import pandas as pd
import ipeadatapy as ip

df_ipea = ip.timeseries('PRECOS12_IPCA12')
df_ipea = df_ipea.reset_index()
df_ipea = df_ipea[df_ipea['YEAR'].between(2010, 2024)]
df_ipea = df_ipea.rename(columns={'YEAR': 'Ano', 'VALUE (-)': 'IPCA'})
df_ipea = df_ipea[['Ano', 'IPCA']]

df_excel = pd.read_csv('empresas_dados.csv', delimiter=';')

df_combinada = pd.merge(df_excel, df_ipea, on='Ano', how='inner')

df_combinada['Receita Real'] = df_combinada['Receita Líquida'] - (
    df_combinada['Receita Líquida'] * (df_combinada['IPCA'] / 100)
)

st.subheader("Tabela com Receita Real ajustada pela inflação (IPCA)")
st.dataframe(df_combinada)

"""6) Crie gráfico de linha que apresente as variáveis Receita Líquida e Receita Real ao longo dos anos (no mesmo gráfico) (peso: 1,0)"""

import matplotlib.pyplot as plt

df_combinada = df_combinada.sort_values(by='Ano')

plt.figure(figsize=(10, 6))
plt.plot(df_combinada['Ano'], df_combinada['Receita Líquida'], marker='o', label='Receita Líquida')
plt.plot(df_combinada['Ano'], df_combinada['Receita Real'], marker='s', label='Receita Real', linestyle='--')

plt.title('Receita Líquida e Receita Real (2010–2024)', fontsize=14)
plt.xlabel('Ano', fontsize=12)
plt.ylabel('Valor (R$)', fontsize=12)
plt.grid(True)
plt.legend()
plt.xticks(df_combinada['Ano'], rotation=45)

plt.tight_layout()
plt.show()

"""7) Faça os ajustes necessários e leve este projeto para a web usando GitHub e Streamlit (peso: 2,0)

- Caça os ajustes necessários no projeto para ser publicado no Streamlit
- Crie novo repositório público no GitHub e leve os arquivos .py e .csv pra lá. Aproveite e crie o arquivo requirements.txt com os pacotes utilizados no projeto
- Crie novo projeto no Streamlit e associe ao repositório da lista
"""
